helm_hpa_5c68b57700f554e7b50b3647c6652c1d:
    enabled: true
    max_replicas: 2
    min_replicas: 1
    name: spring-petclinic-gcp
    target_cpu_utilization_percentage: 50
    target_memory_utilization_percentage: 50
    workload_kind: Deployment
    workload_name: spring-petclinic-gcp
helm_ingress_d3685dc97cd454d1a569ac349b2690d5:
    annotations:
        kubernetes.io/ingress.allow-http: "true"
    default_backend_name: spring-petclinic-gcp
    default_backend_port: 80
    labels:
        service: myapp
    name: spring-petclinic-gcp
    rules: []
    tls: ""
helm_service_37cdd65a28505254a68de58cdcc6303b:
    name: spring-petclinic-gcp
    port: 80
    protocol: TCP
    selector_labels:
        service: myapp
    target_port: 8080
    type: ClusterIP
helm_service_account_6c2de3b51e325bc98a35fccf44ac3ee8:
    annotations: {}
    automount: false
    labels: {}
    name: spring-petclinic-gcp
helm_workload_c0d3ce0f09a052448dab08dcc977ed34:
    env:
        MYSQL_PASS:
        MYSQL_URL:
        MYSQL_USER:
        POSTGRES_PASS: admin@123
        POSTGRES_URL: jdbc:postgresql://10.109.153.3/main
        POSTGRES_USER: admin
        database: main
    env_from_config: []
    env_from_secret: []
    image: "mayurtamhane04/spring-petclinic"
    image_pull_policy: "Always"
    image_pull_secret: my-docker-secret
    image_tag: "3.3.1-SNAPSHOT"
    kind: Deployment
    labels:
        service: myapp
    name: spring-petclinic-gcp
    port: 80
    protocol: TCP
    replicas: 1
    service_account: spring-petclinic-gcp
    volume_mounts: []
    volumes: []